name: Build DB

on:
  push:
    branches: [ master ]
    paths:
      - 'mister_repo_dump.py'
      - 'Makefile'
      - '.github/workflows/go.yml'
  schedule:
    - cron:  '42 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync
    - name: Make database
      run: |
        pipenv run make -j 4
