name: Build DB

on:
  push:
    branches: [ master ]
    paths:
      - 'mister_repo_dump.py'
      - 'Makefile'
      - '.github/workflows/go.yml'
  schedule:
    - cron:  '7/20 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync
    - name: Make database
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBAPI_TOKEN }}
      run: |
        find db -type f -not -name .keep -delete
        pipenv run make -j 4

    - name: Commit and push
      run: |
        git config user.name 'Release Bot'
        git config user.email 'release-bot@databank'
        git add db
        git commit -m "$(date)" && (git push origin master || exit 1) || exit 0
