name: Build DB

on:
  push:
    branches: [ master ]
    paths:
      - 'mister_repo_dump.py'
      - 'Makefile'
      - '.github/workflows/go.yml'
  schedule:
    - cron:  '7/30 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync

    - name: Check API quota (pre-script)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBAPI_TOKEN }}
      run: |
        curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/rate_limit | jq .rate
    - name: Make database
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBAPI_TOKEN }}
      run: |
        make clean
        pipenv run make -j 4 ALL
    - name: Check API quota (post-script)
      if: ${{ always() }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBAPI_TOKEN }}
      run: |
        curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/rate_limit | jq .rate

    - name: Test database
      run: |
        make test
    - name: Commit and push
      run: |
        git config user.name 'Release Bot'
        git config user.email 'release-bot@databank'
        git add db
        git commit -m "$(date)" && (git push origin master || exit 1) || exit 0
